from axon.ui.contracts import OPTION_DESC_KEY, OPTION_KEY
from axon.llm.models import (
    GEMINI_2_5_FLASH,
    GEMINI_2_5_FLASH_LITE,
    GEMINI_2_5_PRO,
    GEMINI_3_1_FLASH_LITE,
    GEMINI_3_1_PRO_PREVIEW,
    GEMINI_3_5_FLASH,
    GEMINI_3_FLASH_PREVIEW,
)

CHAT_LIMIT_OPTIONS = [
    {OPTION_KEY: 10000, OPTION_DESC_KEY: "small"},
    {OPTION_KEY: 20000, OPTION_DESC_KEY: "short"},
    {OPTION_KEY: 50000, OPTION_DESC_KEY: "medium"},
    {OPTION_KEY: 100000, OPTION_DESC_KEY: "large"},
    {OPTION_KEY: 200000, OPTION_DESC_KEY: "huge"},
    {OPTION_KEY: 750000, OPTION_DESC_KEY: "max"}
]

MODEL_OPTIONS = [
    {OPTION_KEY: GEMINI_2_5_FLASH_LITE, OPTION_DESC_KEY: "cheapest | retires Oct 2026"},
    {OPTION_KEY: GEMINI_3_1_FLASH_LITE, OPTION_DESC_KEY: "budget | stable"},
    {OPTION_KEY: GEMINI_2_5_FLASH, OPTION_DESC_KEY: "low cost | retires Oct 2026"},
    {OPTION_KEY: GEMINI_3_FLASH_PREVIEW, OPTION_DESC_KEY: "mid cost | preview"},
    {OPTION_KEY: GEMINI_3_5_FLASH, OPTION_DESC_KEY: "recommended | stable"},
    {OPTION_KEY: GEMINI_2_5_PRO, OPTION_DESC_KEY: "high cost | retires Oct 2026"},
    {OPTION_KEY: GEMINI_3_1_PRO_PREVIEW, OPTION_DESC_KEY: "highest cost | preview"},
]
