from axon.ui.contracts import OPTION_ID_KEY, OPTION_LABEL_KEY
from axon.llm.models import (
    GEMINI_2_5_FLASH,
    GEMINI_2_5_FLASH_LITE,
    GEMINI_2_5_PRO,
    GEMINI_3_1_FLASH_LITE,
    GEMINI_3_1_PRO_PREVIEW,
    GEMINI_3_5_FLASH,
    GEMINI_3_FLASH_PREVIEW,
)

CHAT_LIMIT_OPTIONS = [
    {OPTION_ID_KEY: 10000, OPTION_LABEL_KEY: "10,000 (small)"},
    {OPTION_ID_KEY: 20000, OPTION_LABEL_KEY: "20,000 (short)"},
    {OPTION_ID_KEY: 50000, OPTION_LABEL_KEY: "50,000 (medium)"},
    {OPTION_ID_KEY: 100000, OPTION_LABEL_KEY: "100,000 (large)"},
    {OPTION_ID_KEY: 200000, OPTION_LABEL_KEY: "200,000 (huge)"},
    {OPTION_ID_KEY: 750000, OPTION_LABEL_KEY: "750,000 (max)"}
]

MODEL_OPTIONS = [
    {OPTION_ID_KEY: GEMINI_2_5_FLASH_LITE, OPTION_LABEL_KEY: f"{GEMINI_2_5_FLASH_LITE} (cheapest | retires Oct 2026)"},
    {OPTION_ID_KEY: GEMINI_3_1_FLASH_LITE, OPTION_LABEL_KEY: f"{GEMINI_3_1_FLASH_LITE} (budget | stable)"},
    {OPTION_ID_KEY: GEMINI_2_5_FLASH, OPTION_LABEL_KEY: f"{GEMINI_2_5_FLASH} (low cost | retires Oct 2026)"},
    {OPTION_ID_KEY: GEMINI_3_FLASH_PREVIEW, OPTION_LABEL_KEY: f"{GEMINI_3_FLASH_PREVIEW} (mid cost | preview)"},
    {OPTION_ID_KEY: GEMINI_3_5_FLASH, OPTION_LABEL_KEY: f"{GEMINI_3_5_FLASH} (recommended | stable)"},
    {OPTION_ID_KEY: GEMINI_2_5_PRO, OPTION_LABEL_KEY: f"{GEMINI_2_5_PRO} (high cost | retires Oct 2026)"},
    {OPTION_ID_KEY: GEMINI_3_1_PRO_PREVIEW, OPTION_LABEL_KEY: f"{GEMINI_3_1_PRO_PREVIEW} (highest cost | preview)"},
]
